using Content.Shared._Stalker_EN.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class StalkerEnTab : Control
{
    public StalkerEnTab()
    {
        RobustXamlLoader.Load(this);

        Control.AddOptionCheckBox(STCCVars.EmissionSimpleVisuals, EmissionSimpleVisualsCheckbox);

        Control.Initialize();
    }
}
