- type: entity
  parent: LocalTeleportBase
  id: LocalTeleportBasement5
  suffix: Stalker 5
  name: Чистилище-Сталкер1
  components:
    - type: LocalTeleport
      portalName: Basement5

- type: entity
  parent: LocalTeleportBaseUncollide
  id: LocalTeleportBasement51
  suffix: Stalker 5
  name: Чистилище-Сталкер1 нонколлижн
  components:
    - type: LocalTeleport
      portalName: Basement5

- type: entity
  parent: LocalTeleportBase
  id: LocalTeleportBasement52
  suffix: Stalker 5
  name: Чистилище-Сталкер2
  components:
    - type: LocalTeleport
      portalName: Basement52

- type: entity
  parent: LocalTeleportBaseUncollide
  id: LocalTeleportBasement512
  suffix: Stalker 5
  name: Чистилище-Сталкер2 нонколлижн
  components:
    - type: LocalTeleport
      portalName: Basement52

#############################Военка

- type: entity
  parent: LocalTeleportBase
  id: LocalTeleportMilBase1
  suffix: Stalker 1
  name: Военная база 1
  components:
    - type: LocalTeleport
      portalName: MilBase1

- type: entity
  parent: LocalTeleportBase
  id: LocalTeleportMilBase2
  suffix: Stalker 2
  name: Военная база 2
  components:
    - type: LocalTeleport
      portalName: MilBase2

- type: entity
  parent: LocalTeleportBase
  id: LocalTeleportMilBase3
  suffix: Stalker 3
  name: Военная база 3
  components:
    - type: LocalTeleport
      portalName: MilBase3

################################Подземка Свалки

- type: entity
  parent: LocalTeleportBase
  id: LocalTeleportSvUnderground
  suffix: Stalker 1
  name: Подземелье Свалки 1
  components:
    - type: LocalTeleport
      portalName: SvUnderground

- type: entity
  parent: LocalTeleportBase
  id: LocalTeleportSvUnderground2
  suffix: Stalker 2
  name: Подземелье Свалки 2
  components:
    - type: LocalTeleport
      portalName: SvUnderground2

################################Этажи для жаб
- type: entity
  parent: LocalTeleportBase
  id: LocalTeleportJabasFloors
  suffix: Jaba
  name: Жабий подвал
  components:
    - type: LocalTeleport
      portalName: JabasFloors

################################Вход в базу монолита
- type: entity
  parent: LocalTeleportBase
  id: LocalTeleportmonolith
  suffix: monolith
  name: LocalTeleportmonolith
  components:
    - type: AccessReader
      access: [["Monolith"]]
    - type: LocalTeleport
      portalName: LocalTeleportmonolith

- type: entity
  parent: LocalTeleportBaseUncollide
  id: LocalTeleportmonolithUncollide
  suffix: monolith
  name: LocalTeleportmonolithUncollide
  components:
    - type: AccessReader
      access: [["Bandit"]]
    - type: LocalTeleport
      portalName: LocalTeleportmonolith
