using System;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker_EN.UI.Controls;

/// <summary>
/// Reusable search bar control with a label, text input, and clear button.
/// Fires <see cref="OnSearchTextChanged"/> whenever the search text changes.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class STSearchBarControl : BoxContainer
{
    /// <summary>
    /// Raised whenever the search text changes (typing or clearing).
    /// </summary>
    public event Action<string>? OnSearchTextChanged;

    /// <summary>
    /// The current search text entered by the user.
    /// </summary>
    public string SearchText => SearchLineEdit.Text;

    public STSearchBarControl()
    {
        RobustXamlLoader.Load(this);

        ClearButton.OnPressed += _ => SearchLineEdit.SetText(string.Empty, true);
        SearchLineEdit.OnTextChanged += args => OnSearchTextChanged?.Invoke(args.Text);
    }

    /// <summary>
    /// Programmatically clears the search field and fires the change event.
    /// </summary>
    public void ClearSearch()
    {
        SearchLineEdit.SetText(string.Empty, true);
    }
}
