using Content.Shared._Stalker_EN.FarkleDice;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.Player;

namespace Content.Client._Stalker_EN.FarkleDice;

[GenerateTypedNameReferences]
public sealed partial class STFarkleDiceWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;

    /// <summary>
    /// STALKER PDA amber color used to highlight the active player's name.
    /// </summary>
    private static readonly Color ActivePlayerColor = Color.FromHex("#D4912A");

    private static readonly SoundSpecifier DiceRollSound = new SoundCollectionSpecifier("Dice");

    /// <summary>
    /// Maps preset buttons to their target score values for easy iteration.
    /// </summary>
    private readonly (Robust.Client.UserInterface.Controls.Button Button, int Score)[] _presetButtons;

    private readonly STFarkleDieControl[] _diceControls = new STFarkleDieControl[6];
    private STFarkleDiceBoundUiState? _currentState;

    /// <summary>
    /// Stores previous dice values for detecting when a new roll occurs.
    /// Null on first update to prevent animation on window open mid-game.
    /// </summary>
    private int[]? _previousDiceValues;
    private bool _previousHasRolled;

    public event Action? OnJoinPressed;
    public event Action? OnLeavePressed;
    public event Action? OnRollPressed;
    public event Action<int>? OnDieSelected;
    public event Action? OnKeepAndContinuePressed;
    public event Action? OnBankPressed;
    public event Action? OnNewGamePressed;
    public event Action<int>? OnSetTargetScore;

    public STFarkleDiceWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        for (var i = 0; i < 6; i++)
        {
            var index = i;
            var die = new STFarkleDieControl();
            die.OnPressed += () => OnDieSelected?.Invoke(index);
            _diceControls[i] = die;
            DiceContainer.AddChild(die);
        }

        JoinButton.OnPressed += _ => OnJoinPressed?.Invoke();
        LeaveButton.OnPressed += _ => OnLeavePressed?.Invoke();
        RollButton.OnPressed += _ => OnRollPressed?.Invoke();
        KeepButton.OnPressed += _ => OnKeepAndContinuePressed?.Invoke();
        BankButton.OnPressed += _ => OnBankPressed?.Invoke();
        NewGameButton.OnPressed += _ => OnNewGamePressed?.Invoke();

        // Wire target score preset buttons
        Score5000.OnPressed += _ => OnSetTargetScore?.Invoke(5000);
        Score10000.OnPressed += _ => OnSetTargetScore?.Invoke(10000);
        Score15000.OnPressed += _ => OnSetTargetScore?.Invoke(15000);
        Score20000.OnPressed += _ => OnSetTargetScore?.Invoke(20000);

        _presetButtons = new[]
        {
            (Score5000, 5000),
            (Score10000, 10000),
            (Score15000, 15000),
            (Score20000, 20000),
        };
    }

    public void UpdateState(STFarkleDiceBoundUiState state)
    {
        _currentState = state;

        var isYourTurn = IsLocalPlayersTurn(state);

        TargetScoreLabel.Text = Loc.GetString("farkle-target-score", ("score", state.TargetScore));

        Player1Label.Text = state.Player1Name ?? Loc.GetString("farkle-empty-seat");
        Player2Label.Text = state.Player2Name ?? Loc.GetString("farkle-empty-seat");
        Player1ScoreLabel.Text = state.Player1Score.ToString();
        Player2ScoreLabel.Text = state.Player2Score.ToString();

        var player1Active = state.CurrentPlayer == 1
            && state.Phase != STFarkleDicePhase.WaitingForPlayers
            && state.Phase != STFarkleDicePhase.GameOver;
        var player2Active = state.CurrentPlayer == 2
            && state.Phase != STFarkleDicePhase.WaitingForPlayers
            && state.Phase != STFarkleDicePhase.GameOver;
        Player1Label.Modulate = player1Active ? ActivePlayerColor : Color.White;
        Player2Label.Modulate = player2Active ? ActivePlayerColor : Color.White;

        TurnScoreLabel.Text = state.TurnScore.ToString();

        StatusLabel.Text = GetStatusMessage(state, isYourTurn);

        SelectionScoreLabel.Text = state.SelectedScore > 0
            ? Loc.GetString("farkle-points", ("points", state.SelectedScore))
            : "-";

        var shouldAnimate = DetectNewRoll(state);

        if (shouldAnimate)
            PlayDiceSound();

        for (var i = 0; i < 6; i++)
        {
            var die = _diceControls[i];
            var value = state.DiceValues[i];
            var isKept = state.KeptDice[i];
            var isSelected = state.SelectedDice[i];

            if (!state.HasRolled && value == 0)
            {
                die.SetUnknown();
                die.SetVisualState(DieVisualState.Normal);
                die.Disabled = true;
            }
            else
            {
                var animateThisDie = shouldAnimate && !isKept;
                die.SetValue(value, animateThisDie);

                if (isKept)
                    die.SetVisualState(DieVisualState.Kept);
                else if (isSelected)
                    die.SetVisualState(DieVisualState.Selected);
                else
                    die.SetVisualState(DieVisualState.Normal);

                if (!isYourTurn || state.Phase != STFarkleDicePhase.SelectingDice)
                    die.Disabled = true;
                else if (isKept)
                    die.Disabled = true;
                else
                    die.Disabled = !state.HasRolled;
            }
        }

        _previousDiceValues = (int[]) state.DiceValues.Clone();
        _previousHasRolled = state.HasRolled;

        UpdateTargetScorePresets(state);
        UpdateButtonStates(state, isYourTurn);
    }

    /// <summary>
    /// Shows or hides the target score preset buttons and highlights the active one.
    /// Only visible to the host (Player1) during the WaitingForPlayers phase.
    /// </summary>
    private void UpdateTargetScorePresets(STFarkleDiceBoundUiState state)
    {
        var localPlayer = _playerManager.LocalEntity;
        var isHost = false;

        if (localPlayer != null && state.Player1NetEntity != null)
        {
            var localNetEntity = _entManager.GetNetEntity(localPlayer.Value);
            isHost = localNetEntity == state.Player1NetEntity;
        }

        var showPresets = state.Phase == STFarkleDicePhase.WaitingForPlayers && isHost;
        TargetScorePresets.Visible = showPresets;

        if (!showPresets)
            return;

        // Highlight the currently active preset by disabling it
        foreach (var (button, score) in _presetButtons)
        {
            button.Disabled = state.TargetScore == score;
        }
    }

    /// <summary>
    /// Detects whether a new roll occurred by comparing current and previous state.
    /// Returns false on first call (window opened mid-game) to prevent spurious animation.
    /// </summary>
    private bool DetectNewRoll(STFarkleDiceBoundUiState state)
    {
        if (_previousDiceValues == null)
            return false;

        if (state.HasRolled && !_previousHasRolled)
            return true;

        for (var i = 0; i < 6; i++)
        {
            if (!state.KeptDice[i] && state.DiceValues[i] != _previousDiceValues[i])
                return true;
        }

        return false;
    }

    /// <summary>
    /// Plays the dice roll sound effect once per roll using the Dice sound collection.
    /// </summary>
    private void PlayDiceSound()
    {
        if (_entManager.TrySystem<AudioSystem>(out var audio))
        {
            audio.PlayGlobal(DiceRollSound, Filter.Local(), false);
        }
    }

    private bool IsLocalPlayersTurn(STFarkleDiceBoundUiState state)
    {
        var localPlayer = _playerManager.LocalEntity;
        if (localPlayer == null)
            return false;

        var localNetEntity = _entManager.GetNetEntity(localPlayer.Value);

        var currentPlayerNetEntity = state.CurrentPlayer == 1
            ? state.Player1NetEntity
            : state.Player2NetEntity;

        return currentPlayerNetEntity == localNetEntity;
    }

    private static string GetStatusMessage(STFarkleDiceBoundUiState state, bool isYourTurn)
    {
        return state.Phase switch
        {
            STFarkleDicePhase.WaitingForPlayers => Loc.GetString("farkle-waiting-for-players"),
            STFarkleDicePhase.GameOver => Loc.GetString("farkle-player-wins", ("player", GetWinner(state))),
            _ => isYourTurn
                ? Loc.GetString("farkle-your-turn")
                : Loc.GetString("farkle-opponent-turn")
        };
    }

    private static int GetWinner(STFarkleDiceBoundUiState state)
    {
        return state.Player1Score >= state.TargetScore ? 1 : 2;
    }

    private void UpdateButtonStates(STFarkleDiceBoundUiState state, bool isYourTurn)
    {
        var isWaiting = state.Phase == STFarkleDicePhase.WaitingForPlayers;
        var isGameOver = state.Phase == STFarkleDicePhase.GameOver;
        var isPlaying = !isWaiting && !isGameOver;
        var isInGame = state.Player1Name != null && state.Player2Name != null;

        JoinButton.Visible = isWaiting || isGameOver;
        JoinButton.Disabled = state.Player1Name != null && state.Player2Name != null;

        LeaveButton.Visible = isInGame && !isGameOver;

        RollButton.Visible = isPlaying;
        RollButton.Disabled = !isYourTurn ||
                              state.Phase != STFarkleDicePhase.Rolling ||
                              state.HasRolled;

        KeepButton.Visible = isPlaying;
        KeepButton.Disabled = !isYourTurn ||
                              state.Phase != STFarkleDicePhase.SelectingDice ||
                              state.SelectedScore == 0;

        BankButton.Visible = isPlaying;
        BankButton.Disabled = !isYourTurn ||
                              state.Phase != STFarkleDicePhase.SelectingDice ||
                              (state.TurnScore == 0 && state.SelectedScore == 0);

        NewGameButton.Visible = isGameOver;
    }
}
