using System.Linq;
using Content.Client._Stalker.Shop.Ui.SliderTab;
using Content.Client._Stalker_EN.UI.Controls;
using Content.Client.Actions;
using Content.Client.GameTicking.Managers;
using Content.Client.Message;
using Content.Client.Store.Ui;
using Content.Shared._Stalker.Shop.Prototypes;
using Content.Shared.FixedPoint;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Stalker.Shop.Ui;
/// <summary>
/// Stalker shops client control system, uses for UI updates
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ShopMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IGameTiming _gameTiming = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
    private readonly ClientGameTicker _gameTicker;
    private readonly ActionsSystem _actions;
    private ShopSlider? _shopSlider;

    /// <summary>
    /// Current balance of the shop/user
    /// </summary>
    private int _balance;

    private string _moneyId = string.Empty;
    private string _locMoneyName = string.Empty;
    public event Action<BaseButton.ButtonEventArgs, string>? OnCategoryButtonPressed;
    public event Action<BaseButton.ButtonEventArgs, ListingData, bool, int, int?>? OnListingButtonPressed;
    public event Action? OnRefreshButtonPressed;

    /// <summary>
    /// Current category user chosen, if its null on open, we will take the first one(by priority)
    /// </summary>
    public string? CurrentCategory;
    private const string UserCategory = "UserItems";

    // stalker-changes: cached data for search filtering
    private List<CategoryInfo> _cachedCategories = new();
    private HashSet<ListingData> _cachedUserItems = new();

    public ShopMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();
        _actions = _entityManager.System<ActionsSystem>(); // Need for implants lol
        RefreshButton.OnPressed += _ => OnRefreshButtonPressed?.Invoke();

        // stalker-changes: search bar
        SearchBar.OnSearchTextChanged += _ =>
        {
            ClearListings();
            FilterAndDisplayListings();
        };
    }

    #region Updates
    public void UpdateBalance(int balance, string? moneyId, string? locMoneyName)
    {
        _balance = balance;
        _moneyId = moneyId ?? _moneyId;
        _locMoneyName = locMoneyName ?? _locMoneyName;

        var displayname = Loc.GetString(_locMoneyName);

        // Captialize first letter
        displayname =
            string.Concat(displayname[0].ToString().ToUpper(), displayname.AsSpan(1));

        var balanceStr = Loc.GetString("store-ui-balance-display", ("amount", balance),
            ("currency", displayname));
        BalanceInfo.SetMarkup(balanceStr.TrimEnd());
    }

    public void UpdateListing(List<CategoryInfo> categories, List<ListingData> userItems)
    {
        // stalker-changes: cache for search filtering
        _cachedCategories = categories;
        _cachedUserItems = new HashSet<ListingData>(userItems);
        FilterAndDisplayListings();
    }

    /// <summary>
    /// Filters and displays listings based on the current search text and selected category.
    /// When a search term is active, searches across all categories and user items.
    /// When empty, shows only the selected category (original behavior).
    /// </summary>
    private void FilterAndDisplayListings()
    {
        var filter = SearchBar.SearchText;
        var hasSearch = !string.IsNullOrWhiteSpace(filter);
        var listings = new List<ListingData>();

        if (hasSearch)
        {
            foreach (var cat in _cachedCategories)
                listings.AddRange(cat.ListingItems);

            listings.AddRange(_cachedUserItems);
        }
        else
        {
            foreach (var el in _cachedCategories)
            {
                if (el.Name != CurrentCategory)
                    continue;

                listings.AddRange(el.ListingItems);
            }

            if (CurrentCategory == UserCategory)
                listings.AddRange(_cachedUserItems);
        }

        var sorted = listings
            .Where(l => MatchesSearchFilter(l, filter))
            .OrderBy(l => l.Priority)
            .ThenBy(l => l.OriginalCost.Values.Sum());

        ClearListings();

        foreach (var item in sorted)
        {
            var isSellItem = hasSearch
                ? _cachedUserItems.Contains(item)
                : CurrentCategory == UserCategory;

            AddListingGui(item, isSellItem);
        }
    }

    /// <summary>
    /// Checks whether the listing's resolved name or description matches the search filter.
    /// </summary>
    private bool MatchesSearchFilter(ListingData listing, string? filter)
    {
        if (string.IsNullOrWhiteSpace(filter))
            return true;

        var listingName = listing.Name != null ? Loc.GetString(listing.Name) : string.Empty;
        var listingDesc = listing.Description != null ? Loc.GetString(listing.Description) : string.Empty;

        if (listing.ProductEntity != null
            && _prototypeManager.TryIndex<EntityPrototype>(listing.ProductEntity, out var proto))
        {
            if (string.IsNullOrEmpty(listingName))
                listingName = proto.Name;

            if (string.IsNullOrEmpty(listingDesc))
                listingDesc = proto.Description;
        }

        return STSearchFilter.Matches(filter, listingName, listingDesc);
    }

    private void ClearListings()
    {
        StoreListingsContainer.Children.Clear();
    }
    #endregion

    #region ListingsOperations
    private void AddListingGui(ListingData listing, bool sell = false)
    {
        var listingName = Loc.GetString(listing.Name ?? "");
        var listingDesc = Loc.GetString(listing.Description ?? "");
        var listingPrice = listing.OriginalCost;
        var listingCount = listing.Count; // listing.Count; ST-TODO: I'm not sure that this is correct logic, but I don't want to add the field.
        if (listingPrice is null)
            return;
        var canBuy = !sell ? CanBuyListing(_balance, listingPrice.Values.First()) : sell;

        var spriteSys = _entityManager.EntitySysManager.GetEntitySystem<SpriteSystem>();

        Texture? texture = null;
        if (listing.Icon != null)
            texture = spriteSys.Frame0(listing.Icon);

        if (listing.ProductEntity != null)
        {
            texture ??= spriteSys.GetPrototypeIcon(listing.ProductEntity).Default;
            var proto = _prototypeManager.Index<EntityPrototype>(listing.ProductEntity);

            if (listingName == string.Empty)
                listingName = proto.Name;

            if (listingDesc == string.Empty)
                listingDesc = proto.Description;
        }
        else if (listing.ProductAction != null)
        {
            var actionId = _entityManager.Spawn(listing.ProductAction);
            if (_actions.GetAction(actionId) is { Comp.Icon: not null } action)
                texture = spriteSys.Frame0(action.Comp.Icon);
        }

        var listingInStock = ListingInStock(listing);

        var newListing = new ShopListingControl(listingName, listingDesc, listingInStock, canBuy, sell, texture);
        newListing.ShopItemButton.OnButtonDown += (args) =>
        {
            if (!sell)
            {
                OnListingButtonPressed?.Invoke(args, listing, sell, _balance, null);
                newListing.ShopItemButton.Disabled = true;
                return;
            }

            if (listingCount <= 1)
            {
                OnListingButtonPressed?.Invoke(args, listing, sell, _balance, listingCount);
                return;
            }

            if (_shopSlider != null && _shopSlider.IsOpen)
            {
                _shopSlider.MoveToFront();
                return;
            }
            if (!listing.OriginalCost.TryGetValue(_moneyId, out var money))
                return;

            _shopSlider = new ShopSlider(listingCount, money.Int());
            _shopSlider.OpenCentered();

            _shopSlider.ConfirmButtonPressed += () =>
            {
                OnListingButtonPressed?.Invoke(args, listing, sell, _balance, _shopSlider.GetSliderValue());
            };
        };

        StoreListingsContainer.AddChild(newListing);
    }

    private string GetListingPriceString(ListingData listing)
    {
        var text = string.Empty;
        if (listing.OriginalCost.Count < 1)
            return Loc.GetString("store-currency-free").TrimEnd();

        foreach (var (type, amount) in listing.OriginalCost)
        {

            var currency = _prototypeManager.Index<CurrencyPrototype>(type);
            text += Loc.GetString("store-ui-price-display", ("amount", amount),
                ("currency", Loc.GetString(currency.DisplayName, ("amount", amount))));
        }

        return text.TrimEnd();
    }

    /// <summary>
    /// Return time until available or the cost.
    /// </summary>
    private string ListingInStock(ListingData listing)
    {
        var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);

        var restockTimeSpan = listing.RestockTime;
        if (restockTimeSpan <= stationTime)
            return GetListingPriceString(listing);

        var timeLeftToBuy = stationTime - restockTimeSpan;
        return timeLeftToBuy.Duration().ToString(@"mm\:ss");
    }

    private bool CanBuyListing(int balance, FixedPoint2 price)
    {
        return balance >= price;
    }
    #endregion

    #region CategoryControls
    public void PopulateStoreCategoryButtons(List<CategoryInfo> categories, List<ListingData> items)
    {
        var allCategories = categories;

        allCategories = allCategories.OrderBy(c => c.Priority).ToList();

        if (CurrentCategory == null && allCategories.Count > 0)
            CurrentCategory = allCategories.First().Name;

        if (allCategories.Count <= 1)
            return;

        CategoryListContainer.Children.Clear();

        foreach (var category in allCategories)
        {
            var catButton = new ShopCategoryButton
            {
                Text = Loc.GetString(category.Name),
                CategoryInfo = category,
            };

            catButton.OnPressed += args => OnCategoryButtonPressed?.Invoke(args, catButton.CategoryInfo.Name);
            CategoryListContainer.AddChild(catButton);
        }

        // Sell items category
        var youCategory = new ShopCategoryButton
        {
            Text = Loc.GetString("shop-your-items-category"),
            CategoryInfo = new CategoryInfo
            {
                Items = new Dictionary<string, int>(),
                Name = UserCategory
            }
        };

        youCategory.OnPressed += args => OnCategoryButtonPressed?.Invoke(args, youCategory.CategoryInfo.Name);
        CategoryListContainer.AddChild(youCategory);
    }

    private sealed class ShopCategoryButton : Button
    {
        public CategoryInfo? CategoryInfo;
    }
    #endregion
}
