- type: accessLevel
  id: Project
  name: id-card-access-level-project

- type: accessLevel
  id: ProjectOrchestrator
  name: id-card-access-level-project-orchestrator

- type: accessLevel
  id: ProjectPawn
  name: id-card-access-level-pawn
